In [24]:
execfile("/home/mathias/programming/almost-infinite-sites-recursions/configurations.py")

In [30]:
A, nR, nC = np.matrix([[0,2],[3,1]]), np.array([999,2]), np.array([998,3])
A,nR,nC

(matrix([[0, 2],
         [3, 1]]), array([999,   2]), array([998,   3]))

In [31]:
phi = configuration_new(A,nR,nC)
print(phi)

 998 3 
 - o  ||  999
 x +  ||  2


In [32]:
phiMut,Nr,Nc = mutation_new(phi,1,1,0)

After step 1
[[0 2 2]
 [3 1 1]
 [3 1 0]]
[999   1   1]
[998   2   1]

After step 2.1 (remove rows w multiplicity 0)
[[0 2 2]
 [3 1 1]
 [3 1 0]]
[999   1   1]
[998   2   1]

After step 2.2 (remove cols w. multiplicity 0)
[[0 2 2]
 [3 1 1]
 [3 1 0]]
[999   1   1]
[998   2   1]

After step 3.1 (merge identical rows)
[[0 2 2]
 [3 1 1]
 [3 1 0]]
[999   1   1]
[998   2   1]

After step 3.2 (merge identical columns)
[[0 2 2]
 [3 1 1]
 [3 1 0]]
[999   1   1]
[998   2   1]



In [33]:
print(phiMut)

 998 2 1 
 - o o  ||  999
 x + +  ||  1
 x + -  ||  1


In [34]:
Nr,Nc

(1, 1)

In [18]:
A[:,-1]

matrix([[2],
        [1]])

In [35]:
phiMut1,Nr1,Nc1 = mutation_new(phiMut,1,1,0)

After step 1
[[0 2 2 2]
 [3 1 1 1]
 [3 1 0 1]
 [3 1 1 0]]
[999   0   1   1]
[998   1   1   1]

After step 2.1 (remove rows w multiplicity 0)
[[0 2 2 2]
 [3 1 0 1]
 [3 1 1 0]]
[999   1   1]
[998   1   1   1]

After step 2.2 (remove cols w. multiplicity 0)
[[0 2 2 2]
 [3 1 0 1]
 [3 1 1 0]]
[999   1   1]
[998   1   1   1]

After step 3.1 (merge identical rows)
[[0 2 2 2]
 [3 1 0 1]
 [3 1 1 0]]
[999   1   1]
[998   1   1   1]

After step 3.2 (merge identical columns)
[[0 2 2 2]
 [3 1 0 1]
 [3 1 1 0]]
[999   1   1]
[998   1   1   1]



In [36]:
print(phiMut1)

 998 1 1 1 
 - o o o  ||  999
 x + - +  ||  1
 x + + -  ||  1


In [38]:
type(phiMut1)

__main__.configuration_new